---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    ansible_user: root
    debian_setup_host: ""  # Docker container can't set hostname
    debian_setup_timezone: ""  # Docker container can't set timezone
  roles:
    - role: fred_drake.debian_setup
