---
name: CI
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
defaults:
  run:
    working-directory: .

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Check Dockerfile with Hadolint
        run: docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile

# - name: Set up Python 3.10.13
#   uses: actions/setup-python@v5
#   with:
#     python-version: "3.10"
# - name: Install dependencies
#   run: pip install yamllint ansible-lint

# - name: Check all yaml with yamllint
#   run: yamllint .

# - name: Call lint operation
#   run: >
#     docker run
#     -v .:/workspaces/ansible-role-debian-setup
#     --rm my-docker-image just lint
# test:
#   runs-on: ubuntu-latest
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Build Docker image
#       run: docker build -t my-docker-image .

#     - name: Call test operation
#       run: >
#         docker run
#         -v /var/run/docker.sock:/var/run/docker.sock
#         -v .:/workspaces/ansible-role-debian-setup
#         --rm my-docker-image just test
